// Node Centering Debug Guide
console.log('🔍 Node Centering Debug Analysis')
console.log('=====================================')

console.log('')
console.log('📋 What to check in Browser Developer Console:')
console.log('')

console.log('1. 🎯 POSITIONING CALCULATIONS:')
console.log('   Look for messages starting with: "🔍 Debug node"')
console.log('   These show:')
console.log('   - Base position (grid coordinates)')
console.log('   - Center offsets (should be x=20, y=7)')
console.log('   - Final position (base + offset)')
console.log('')

console.log('2. 📏 ACTUAL RENDERED DIMENSIONS:')
console.log('   Look for messages starting with: "📏 Actual rendered dimensions"')
console.log('   These show:')
console.log('   - getBoundingClientRect dimensions')
console.log('   - Computed CSS width/height')
console.log('   - Padding and border values')
console.log('   - Actual position on screen')
console.log('')

console.log('3. 🔬 EXPECTED VALUES:')
console.log('   - Grid cell: 220px × 50px')
console.log('   - Node config: 180px × 36px') 
console.log('   - Center offsets: X=20px, Y=7px')
console.log('   - With padding (0.5rem ≈ 8px) and border (2px):')
console.log('     Total border+padding = 4px + 16px = 20px')
console.log('     Content area = 180px - 20px = 160px')
console.log('')

console.log('4. 🚨 POTENTIAL ISSUES TO LOOK FOR:')
console.log('   ❌ Computed width ≠ 180px (CSS override)')
console.log('   ❌ Center offsets ≠ 20px/7px (calculation error)')  
console.log('   ❌ Position not matching calculations (CSS conflicts)')
console.log('   ❌ Padding in rem not converting to expected px (8px)')
console.log('')

console.log('5. 💡 DEBUGGING STEPS:')
console.log('   1. Open browser DevTools (F12)')
console.log('   2. Go to Console tab')
console.log('   3. Navigate to: http://localhost:5173/TimeHeroSim2/#/upgrade-tree')
console.log('   4. Look for the debug messages above')
console.log('   5. Compare actual vs expected values')
console.log('')

console.log('6. 🎯 HYPOTHESIS TO TEST:')
console.log('   The nodes have padding (0.5rem) + border (2px) = ~20px extra')
console.log('   This might not be accounted for in centering calculations')
console.log('   OR the inline styles might not be overriding CSS properly')

console.log('')
console.log('✅ Ready to debug! Check browser console after loading upgrade tree.')
